### ISSUE TITLE
Padding and menu background issues

### ISSUE THREAD

**Issue by dokax** [black7375/Firefox-UI-Fix#136]
**Describe the bug**

**Expected behavior**

**Screenshots**
[https://imgur.com/a/qmUXsWa](https://imgur.com/a/qmUXsWa)
![image](https://user-images.githubusercontent.com/25581533/128711106-65d2e09f-0f75-4534-a275-65c3396e14af.png)
![image](https://user-images.githubusercontent.com/25581533/128711117-85e7fc2b-177f-4155-a692-ea4e7df5bb70.png)
![image](https://user-images.githubusercontent.com/25581533/128711128-c8866cab-6281-4670-8496-d04b91aa2cd1.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**

**Comment by Vulatera** [comment]
Same issue on Photon Style and Proton Style.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/128732489-36587381-4388-4df6-8b63-73e6f1f033f6.png)
Bookmarks menu now well visible

---

How can I check the second and third?
- Second: I don't know what the menu is.
- In my browser, the `Repair text encoding` button is displayed as disabled.

**Comment by dokax** [comment]
> How can I check the second and third?

Ctrl+H -> View

>     * In my browser, the `Repair text encoding` button is displayed as disabled.

I don't know why it's disabled in yours, I'm on Firefox 90.0.2

**Comment by black7375** [comment]
Thank you for the information.
I'll try to find the relevant information tomorrow.

**Comment by black7375** [comment]
History sorting menu should work fine now
![image](https://user-images.githubusercontent.com/25581533/128887612-ae3840ad-83cd-4306-95ff-f7eb1bc447bf.png)

But as I said before, the `Repair text encoding` button is still disabled, so I'm not sure.

**Comment by Vulatera** [comment]
I can confirm that bookmarks menu bug was fixed with this commit https://github.com/black7375/Firefox-UI-Fix/commit/c458c4408b47585dcdbdfd0d6d3cf93047c20212
But with the release of v3.0.0 it is not fixed.

**Comment by AntonZur** [comment]
Bookmarks menu bug was fixed, but shadow error in folders in Bookmarks Bar still alive.
![001](https://user-images.githubusercontent.com/88890316/129370592-f49a2fb9-443e-47df-9edb-18759c5a2ef5.jpg)

**Comment by black7375** [comment]
@AntonZur 
Added as an exception!
Thanks for the detailed report with screenshots.

---

@Vulatera 
Could you test next steps?

1. Run Browser Toolbox after activate
https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox
2. menupopup's style
![image](https://user-images.githubusercontent.com/25581533/129369417-73d4534c-84a5-49e1-ae3f-b24d144a7039.png)
```css
/* My environment */
menupopup {
    appearance: none;
    -moz-window-shadow: cliprounded;
    background-color: transparent;
    border: none;
    border-radius: 4px;
    --panel-color: var(--menu-color);
    --panel-border-radius: 4px;
    --panel-padding: 4px 0;
    --panel-border-color: var(--menu-border-color);
    --panel-background: var(--menu-background-color);
    --nested-margin: -6px;
}
```
3. arrowscrollbox's style
![image](https://user-images.githubusercontent.com/25581533/129369629-25c06ece-4f40-4de6-82e5-24d5ae1a5b25.png)
```css
/* My environment */
:is(panel, menupopup)::part(content) {
    display: -moz-box;
    -moz-box-flex: 1;
    padding: var(--panel-padding);
    color: var(--panel-color);
    background: var(--panel-background);
    border-radius: var(--panel-border-radius);
    border: 1px solid var(--panel-border-color);
    width: var(--panel-width);
}
```
4. test
![image](https://user-images.githubusercontent.com/25581533/129370169-d6b1e65d-2492-42db-968a-13d6e9bd2107.png)
```css
:root,
menupopup {
  --panel-color: var(--menu-color) !important;
  --panel-background: var(--menu-background-color) !important;
}
.menupopup-arrowscrollbox {
  color: var(--panel-color) !important;
  background: var(--panel-background) !important;
}
```
If my guess is correct, the following script should work.

Improved compatibility will help many people.

**Comment by Vulatera** [comment]
@black7375
Ok with these steps I am unable to cope with due to the fact my experience in CSS is on a greenhorn level. 
Hopefully someone else with more knowledge can do the test.

**Comment by black7375** [comment]
@dokax 
> Sorting menu is fixed now, but [bookmarks menu](https://imgur.com/cNKCYbP) and repair text encoding menu are still not fixed.

Maybe it has been fixed!!

Thanks for the report.
A little late.

---

We are now closing this issue as we believe it has all been resolved.
Other branches(`photon-style`, `proton-style`) will be reflected tomorrow.

**Comment by dokax** [comment]
> Maybe it has been fixed!!

No, it's still not fixed.
https://imgur.com/9pPPo7R

**Comment by dokax** [comment]
Just let you know that I installed the latest version , but it seems still not fixed.

Commits ebe9043 and e92046b seems not working for me.

Thank you for your effort.

**Comment by black7375** [comment]
Bookmark menu is `menu`, but it is a kind of edge case that looks like `panel`, so there are many exceptions.
There was a review of the overall code and it now works on https://github.com/black7375/Firefox-UI-Fix/commit/4e4b27d9178ec8d89f49baa7b16248ebe615a56e for me.

But looking at the [screenshot](https://github.com/black7375/Firefox-UI-Fix/issues/136#issuecomment-902031747) of OP, the icons are strangely narrow.
https://github.com/black7375/Firefox-UI-Fix/blob/69cbe1db2c1a54da34d28994d1f1ff60655ca4c0/userChrome.css#L1606-L1607

In my code, if icons exist, I intentionally exclude it from the padding, margin adjust.

**Comment by dokax** [comment]
> There was a review of the overall code and it now works on [4e4b27d](https://github.com/black7375/Firefox-UI-Fix/commit/4e4b27d9178ec8d89f49baa7b16248ebe615a56e) for me.

It doesn't work for me.

I'm using Win10 21H1 19043.1165

**Comment by black7375** [comment]
It seems to work fine in the latest version.
