### ISSUE TITLE
Missing icons at Manage Bookmark & History Library

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#739]
### Describe the bug

At `Manage Bookmark & History Library` (Open by pressing `Ctrl`+`Shift`+`O`), the `Redo` and `Restore` icons are missing.

### Expected behavior

The `Redo` and `Restore` icons are present to make the UI more consistent.

### Screenshots

<img width="608" alt="Screenshot 2023-07-07 122335" src="https://github.com/black7375/Firefox-UI-Fix/assets/109966292/1522b73f-bd26-4ac3-bd5c-f52be5bd5756">
<img width="608" alt="Screenshot 2023-07-07 122344" src="https://github.com/black7375/Firefox-UI-Fix/assets/109966292/c44a0281-df58-4fba-8251-b03418bc2fdb">

### OS

Windows 11

### Firefox Version

v117.0a1

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
The `redo` menu is an intentional decision as empty looks better than stuffed.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/7396a683-c79a-471e-b1f8-9bffb70f81c6)

If do you want, set
- `userChrome.icon.menu.full` to `true`

---

`Restore` could not find a suitable icon, so it probably doesn't exist yet.

**Comment by Progress200** [comment]
Even I follow your guide, the restore icon is still missing.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/b4bc2ee0-541b-453e-8adf-bff2de49f37a)

**Comment by black7375** [comment]
I've added icons.
I released it, so check it out !!

**Comment by Progress200** [comment]
I tried on the newest release and the icon still doesn't appear. (Firefox 118.0a1, Lepton v7.50 with #744 quick fix)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/5d607637-abb2-426c-9755-23c9b28f1b4e)

**Comment by black7375** [comment]
@Progress200 Can you check followings?

1. `userChrome.icon.menu.full` to `true`
2. `<PROFILE_PATH>/chrome/icons/datarestore.svg` is exist https://github.com/black7375/Firefox-UI-Fix/commit/276510d732ec447543aeaf5ce063df65c1dff93b#diff-093c15cbf08255fc91625b98349e24f1e0c9806099fe8f3f806382a79764da98


![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/4eefae17-667a-4b86-bf7c-f427df03d9d9)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/550769a4-19d5-4430-b2a6-f69c806bf22c)

**Comment by Progress200** [comment]
I set `userChrome.icon.menu.full `to true and it works now. Thank you!
