### ISSUE TITLE
Tooltip when mouse-overing a tab has no background fill, completely transparent background

### ISSUE THREAD

**Issue by Dwedit** [black7375/Firefox-UI-Fix#890]
### Describe the bug

This is one is new for Firefox 126.

When you mouseover a tab, you normally get a tooltip.  The tooltips are broken at the moment, instead of having an opaque background, it is missing any opacity at all, resulting in black text on a completely clear background.

### Expected behavior

Should have a fill style defined for the tooltip (the same color as the toolbar and tab)

### Screenshots

![firefox_ui_fix_bug](https://github.com/black7375/Firefox-UI-Fix/assets/1743498/5682be78-f04c-481d-8a5c-f561ad9423f4)

### OS

Windows 10

### Firefox Version

126.0

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

Tested on a fresh profile with just those files extracted.

**Comment by erwin4270** [comment]
Have the same issue here, it also happens when using certain dynamic themes [like this one](https://addons.mozilla.org/addon/nicothin-space/)

**Comment by erwin4270** [comment]
I think this is an issue in Firefox. I tested this by creating a new profile without Lepton and using [Firefox Color](https://color.firefox.com). If the toolbar color alpha ([`toolbar`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors)) of the theme is 0%, it's transparent

**Comment by erwin4270** [comment]
I tested this using [Firefox Color](https://color.firefox.com).

If the toolbar color alpha (`toolbar`) of the theme is 0%, it's transparent.
![0a](https://github.com/black7375/Firefox-UI-Fix/assets/104198709/653f7a90-40d4-4dd6-a55f-56dcead5f80a)

In the latest Nightly, if the popup background alpha (`popup`) of the theme is 0%, it's transparent

**Comment by black7375** [comment]
@erwin4270 Thanks. This should make reproduction very easy, thanks for the comment.
I'll try to fix the bug over the weekend.

**Comment by black7375** [comment]
Fixed to base the color of the panel(popup) instead of the toolbar.

**Comment by walking-octopus** [comment]
Fix still not ported to Photon.
![Screenshot_20240527_171923](https://github.com/black7375/Firefox-UI-Fix/assets/46994949/cbc723cf-0fee-4d83-b817-01e57222c0cf)
Reproduced on latest master.

**Comment by fraencko** [comment]
Can confirm that the issue is there on Windows 11, Photon and Proton style, latest master.
![tooltip-bug](https://github.com/black7375/Firefox-UI-Fix/assets/67413205/937e0fae-637e-4dbf-9366-60d8b4a4288d)

**Comment by tml3nr** [comment]
It's ok when i rollback v8.6.0.

Windows 10, Firefox 127.0 32bit, Lepton v8.6.0.

![2024-06-16_070013](https://github.com/black7375/Firefox-UI-Fix/assets/18502030/b586100f-fcaa-4f3c-800c-d5e46acaadb3)

**Comment by Dwedit** [comment]
This issue seems to no longer happen in Firefox 127.0.2?

**Comment by black7375** [comment]
Probably. I've also applied a patch to fix the issue.
Try to new release.
- https://github.com/black7375/Firefox-UI-Fix/releases/tag/v8.6.2
